# Site settings
title: Nga Là Con Mèo Đấy!
email: huypq104@gmail.com
phone: +841213866888
description: > # this means to ignore newlines until "url:"
  Những điều bé nhỏ của Ngaooooo
url: "http://www.ngaaaaalaconmeooooo" # the base hostname & protocol for your site
author: Nga Nguyen Thanh
github_username: f-ma

# Plugins

# Conversion
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# Markdown Processors
kramdown:
  input: GFM
