# Site settings
title: Đừng hút thuốc!
email: huypq104@gmail.com
phone: +841213866888
description: > # this means to ignore newlines until "url:"
  Xin đừng hút
url: "http://www.ngaaaaalaconmeooooo" # the base hostname & protocol for your site
author: Pham Quang Huy
github_username: f-ma

# Plugins

# Conversion
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# Markdown Processors
kramdown:
  input: GFM
